import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";
import { Toaster } from '@timex/components/ui/toaster'

import { cn } from "@timex/utils";

// export const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-neutral-100"
          // fontSans.variable
        )}
      >
        <main className="">
        {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
