/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_scheduledetails_free(a: number): void;
export function __wbg_get_scheduledetails_scheduled_start_date_time(a: number, b: number): void;
export function __wbg_set_scheduledetails_scheduled_start_date_time(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_repeat_every(a: number): number;
export function __wbg_set_scheduledetails_repeat_every(a: number, b: number): void;
export function __wbg_get_scheduledetails_repeat_every_number(a: number): number;
export function __wbg_set_scheduledetails_repeat_every_number(a: number, b: number): void;
export function __wbg_get_scheduledetails_end_option(a: number): number;
export function __wbg_set_scheduledetails_end_option(a: number, b: number): void;
export function __wbg_get_scheduledetails_end_date(a: number, b: number): void;
export function __wbg_set_scheduledetails_end_date(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_occurrence_value(a: number, b: number): void;
export function __wbg_set_scheduledetails_occurrence_value(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_week_days_for_repeat_every(a: number, b: number): void;
export function __wbg_set_scheduledetails_week_days_for_repeat_every(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_month_options(a: number): number;
export function __wbg_set_scheduledetails_month_options(a: number, b: number): void;
export function __wbg_get_scheduledetails_on_day_value_for_month(a: number, b: number): void;
export function __wbg_set_scheduledetails_on_day_value_for_month(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_day_category_for_month(a: number): number;
export function __wbg_set_scheduledetails_day_category_for_month(a: number, b: number): void;
export function __wbg_get_scheduledetails_week_day_for_month(a: number): number;
export function __wbg_set_scheduledetails_week_day_for_month(a: number, b: number): void;
export function __wbg_get_scheduledetails_year_options(a: number, b: number): void;
export function __wbg_set_scheduledetails_year_options(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_month_with_day_for_year(a: number, b: number): void;
export function __wbg_set_scheduledetails_month_with_day_for_year(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_on_day_value_for_year(a: number, b: number): void;
export function __wbg_set_scheduledetails_on_day_value_for_year(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_day_category_for_year(a: number, b: number): void;
export function __wbg_set_scheduledetails_day_category_for_year(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_week_day_for_year(a: number, b: number): void;
export function __wbg_set_scheduledetails_week_day_for_year(a: number, b: number, c: number): void;
export function __wbg_get_scheduledetails_month_with_week_day_for_year(a: number, b: number): void;
export function __wbg_set_scheduledetails_month_with_week_day_for_year(a: number, b: number, c: number): void;
export function showDetailInDisplay(a: number, b: number): void;
export function find_schedule_date_time(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
