name: deploy to gh page
on:
    push:
        branches:
            - web-asm
    pull_request:

permissions:
    contents: write
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [20.x]
        defaults:
            run:
                working-directory: ./server/web
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            # - name: Change folder location
            #   id: web-folder
            #   run: |
            #      echo "path=./server/web" >> $GITHUB_OUTPUT
            #      exit 0
            - name: Setup Node  ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version:  ${{ matrix.node-version }}
                cache: npm
                cache-dependency-path: ./server/web
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./out
              
            
            
                    